### ISSUE TITLE
Extension doesn't work in Firefox ESR 128.13.0

### ISSUE THREAD

**Issue by javierhb23** [javierhb23/squeeze#7]
Extension doesn't apply styles to any websites.

Console log:
```
Uncaught (in promise) TypeError: RegExp.escape is not a function
```
